[chef-client]
plan_path = "habitat/chef-infra-client"
build_targets = [
  "x86_64-linux",
  "x86_64-linux-kernel2"
]
paths = [
  "bin",
  "chef-bin",
  "chef-config",
  "ci",
  "distro",
  "ext",
  "habitat-packages",
  "lib",
  "omnibus", # TODO: Evaluate if we really need this in the future
  "tasks",
]
