language: ruby
cache: bundler

sudo: false

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

before_install:
  - gem update bundler

branches:
  only:
    - master

script: bundle exec rspec --color --format progress
