language: ruby
cache: bundler

sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2
before_install:
  - gem update bundler

branches:
  only:
    - master

script: bundle exec rspec --color --format progress
